### ISSUE TITLE
Export to PDF gives fatal error.

### ISSUE THREAD

**Issue by CvdWeter** [fearless359/simpleinvoices#113]
Hi all,

I try to get the 2023 version to work but run into a problem (see error below):

Fatal error: Uncaught Error: Call to undefined function Mpdf\Writer\gzcompress() in /volume1/web/simpleinvoices/vendor/mpdf/mpdf/src/Writer/FontWriter.php:288 Stack trace: #0 /volume1/web/simpleinvoices/vendor/mpdf/mpdf/src/Writer/ResourceWriter.php(113): Mpdf\Writer\FontWriter->writeFonts() #1 /volume1/web/simpleinvoices/vendor/mpdf/mpdf/src/Mpdf.php(10068): Mpdf\Writer\ResourceWriter->writeResources() #2 /volume1/web/simpleinvoices/vendor/mpdf/mpdf/src/Mpdf.php(2066): Mpdf\Mpdf->_enddoc() #3 /volume1/web/simpleinvoices/vendor/mpdf/mpdf/src/Mpdf.php(9524): Mpdf\Mpdf->Close() #4 /volume1/web/simpleinvoices/Inc/Claz/Pdf.php(58): Mpdf\Mpdf->Output('Factuur_2024006...', 'D') #5 /volume1/web/simpleinvoices/Inc/Claz/Export.php(111): Inc\Claz\Pdf::generate('

Anyone an idea how to solve this?

Thanks and kind regards,
Cor

**Comment by fearless359** [comment]
I just tried this on a new setup based on the current master_2023 version and it worked without error. If you are still encountering this problem, please report it in the simpleinvoices.group forum.
